server:
  port: 8080

spring:
  application:
    name: whiteboard-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/whiteboard_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

whiteboard:
  redis:
    channels:
      draw: whiteboard:draw
